# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Build library
      run: go build -v ./...

    - name: Test library
      run: go test -v ./...

    - name: Build linter package
      working-directory: errstklint
      run: go build -v ./...

    - name: Test linter package
      working-directory: errstklint
      run: go test -v ./...

    - name: Build linter CLI
      working-directory: cmd/errstklint
      run: go build -v ./...

    - name: Test linter CLI
      working-directory: cmd/errstklint
      run: go test -v ./...
